version: '3.9'

services:
  spring-backend:
    image: ruantarciisio/imageliteback:latest
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SMTP_MAIL=${SMTP_MAIL}
      - SMTP_PASS=${SMTP_PASS}
      - app.base-url=http://localhost:8080
    depends_on:
      - db-postgres

  next-frontend:
    image: ruantarciisio/imagelitefront:latest
    container_name: next-frontend
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring-backend
      - next-frontend
  db-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: imageliteapi
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
