spring: 
  datasource: 
    url: jdbc:postgresql://localhost:5432/imageliteapi
    username: postgres
    password: senh@BD  
  jpa: 
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  servlet: 
    multipart: 
      max-file-size: 20MB
      max-request-size: 20MB
  


#spring.datasource.url=jdbc:postgresql://localhost:5432/imageliteapi
#spring.datasource.username=postgres
#spring.datasource.password=senh@BD

#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.open-in-view=false


#api.security.token.secret = 98b3a9198243172be6a1ecb688567f9905c93250f489c1fa0a4bab507956ebea 
#api.security.token.expiration = 864000000
#api.security.token.secret = ${JWT_SECRET}