spring:
  profiles:
    active:

  datasource:
    url: jdbc:postgresql://localhost:5432/imageliteapi
    username: postgres
    password: senh@BD
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-name: Google
            authorization-grant-type: authorization_code
            scope: profile,email
            redirect-uri: ${app.base-url}/login/oauth2/code/google
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_MAIL}
    password: ${SMTP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.web: DEBUG

app:
  application-name: ImageLite
  base-url: http://localhost:8080
  allowed-origins: http://localhost:3000
  login-page-url: ${app.base-url}/auth/login
  login-success-url: http://localhost/callback
