app:
  application-name: ImageLite
  base-url: http://localhost:8080
  allowed-origins: https://image-lite-api-front.vercel.app
  login-page-url: ${app.base-url}/auth/login
  login-success-url: https://image-lite-api-front.vercel.app/callback